# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [27]:
# import library
import numpy as np

#### 2. Print your NumPy version.

In [28]:
np.version.version

'1.22.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [29]:
a = np.random.random(size = (2,3,5))
a

array([[[0.27154121, 0.48740489, 0.29178834, 0.08973466, 0.31777458],
        [0.86051572, 0.71658632, 0.48224967, 0.41909602, 0.87562988],
        [0.1923264 , 0.25071702, 0.31895819, 0.26667555, 0.32056258]],

       [[0.10707206, 0.35715371, 0.47940168, 0.08312859, 0.58915575],
        [0.26467975, 0.052318  , 0.93198004, 0.92207849, 0.69830315],
        [0.77387413, 0.4869997 , 0.19838965, 0.29087604, 0.63083204]]])

In [30]:
# Method 2
np.random.rand(2,3,5)

array([[[0.73023411, 0.88121955, 0.07820761, 0.34464989, 0.95715909],
        [0.66752599, 0.27519536, 0.45007348, 0.00683328, 0.86446766],
        [0.67528221, 0.21101423, 0.30912561, 0.59193032, 0.82230411]],

       [[0.63358498, 0.70383007, 0.88502058, 0.3614768 , 0.86546036],
        [0.06575215, 0.87977502, 0.9943902 , 0.58768506, 0.44667747],
        [0.0255915 , 0.05306012, 0.48781038, 0.50558674, 0.4305677 ]]])

In [31]:
# Method 3
np.random.randn(2,3,5)

array([[[-0.21629538, -0.98403886,  1.6498929 , -0.8516862 ,
         -0.40238566],
        [ 0.95401251, -0.92941654,  0.6786437 , -0.64479518,
         -0.07917475],
        [-0.3755694 ,  2.19397092,  1.01498123, -0.06053457,
          1.08865466]],

       [[ 0.09221261, -0.07796416, -0.34326007, -1.60334852,
         -0.52253844],
        [-0.64190065, -1.78268624, -0.5988782 , -0.3429269 ,
         -1.13696693],
        [ 1.09382053, -0.46207192, -2.14962558, -1.11170334,
          0.23923114]]])

#### 4. Print *a*.


In [32]:
print(a)

[[[0.27154121 0.48740489 0.29178834 0.08973466 0.31777458]
  [0.86051572 0.71658632 0.48224967 0.41909602 0.87562988]
  [0.1923264  0.25071702 0.31895819 0.26667555 0.32056258]]

 [[0.10707206 0.35715371 0.47940168 0.08312859 0.58915575]
  [0.26467975 0.052318   0.93198004 0.92207849 0.69830315]
  [0.77387413 0.4869997  0.19838965 0.29087604 0.63083204]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [33]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [34]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [35]:
print(a.shape)
print(b.shape)
a.shape == b.shape

(2, 3, 5)
(5, 2, 3)


False

In [36]:
print(a.size)
print(b.size)
a.size == b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [37]:
c = a + b
# can't add since they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [38]:
# your code here
c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [39]:
cc = np.transpose(b, (1, 2, 0))
cc.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
d = a + c
d
# it works because they have the same shape

array([[[1.27154121, 1.48740489, 1.29178834, 1.08973466, 1.31777458],
        [1.86051572, 1.71658632, 1.48224967, 1.41909602, 1.87562988],
        [1.1923264 , 1.25071702, 1.31895819, 1.26667555, 1.32056258]],

       [[1.10707206, 1.35715371, 1.47940168, 1.08312859, 1.58915575],
        [1.26467975, 1.052318  , 1.93198004, 1.92207849, 1.69830315],
        [1.77387413, 1.4869997 , 1.19838965, 1.29087604, 1.63083204]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
print(a)
print(d)

# the value of d the value of a +1 

[[[0.27154121 0.48740489 0.29178834 0.08973466 0.31777458]
  [0.86051572 0.71658632 0.48224967 0.41909602 0.87562988]
  [0.1923264  0.25071702 0.31895819 0.26667555 0.32056258]]

 [[0.10707206 0.35715371 0.47940168 0.08312859 0.58915575]
  [0.26467975 0.052318   0.93198004 0.92207849 0.69830315]
  [0.77387413 0.4869997  0.19838965 0.29087604 0.63083204]]]
[[[1.27154121 1.48740489 1.29178834 1.08973466 1.31777458]
  [1.86051572 1.71658632 1.48224967 1.41909602 1.87562988]
  [1.1923264  1.25071702 1.31895819 1.26667555 1.32056258]]

 [[1.10707206 1.35715371 1.47940168 1.08312859 1.58915575]
  [1.26467975 1.052318   1.93198004 1.92207849 1.69830315]
  [1.77387413 1.4869997  1.19838965 1.29087604 1.63083204]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [42]:
e = a*c
e

array([[[0.27154121, 0.48740489, 0.29178834, 0.08973466, 0.31777458],
        [0.86051572, 0.71658632, 0.48224967, 0.41909602, 0.87562988],
        [0.1923264 , 0.25071702, 0.31895819, 0.26667555, 0.32056258]],

       [[0.10707206, 0.35715371, 0.47940168, 0.08312859, 0.58915575],
        [0.26467975, 0.052318  , 0.93198004, 0.92207849, 0.69830315],
        [0.77387413, 0.4869997 , 0.19838965, 0.29087604, 0.63083204]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [43]:
e == a
# yes they have the same values

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9319800399235256
1.0523179988125955
1.4342601271633149


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [45]:
# the value inside is just placeholder
f = np.empty((2,3,5))
f

array([[[0.27154121, 0.48740489, 0.29178834, 0.08973466, 0.31777458],
        [0.86051572, 0.71658632, 0.48224967, 0.41909602, 0.87562988],
        [0.1923264 , 0.25071702, 0.31895819, 0.26667555, 0.32056258]],

       [[0.10707206, 0.35715371, 0.47940168, 0.08312859, 0.58915575],
        [0.26467975, 0.052318  , 0.93198004, 0.92207849, 0.69830315],
        [0.77387413, 0.4869997 , 0.19838965, 0.29087604, 0.63083204]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [46]:
f[(d_mean > d) & (d_min < d)] = 25
f[(d_mean < d) &  (d_max > d)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [49]:
print('d:')
print(d)

print('f:')
print(f)

d:
[[[1.27154121 1.48740489 1.29178834 1.08973466 1.31777458]
  [1.86051572 1.71658632 1.48224967 1.41909602 1.87562988]
  [1.1923264  1.25071702 1.31895819 1.26667555 1.32056258]]

 [[1.10707206 1.35715371 1.47940168 1.08312859 1.58915575]
  [1.26467975 1.052318   1.93198004 1.92207849 1.69830315]
  [1.77387413 1.4869997  1.19838965 1.29087604 1.63083204]]]
f:
[[[ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 25.   0. 100.  75.  75.]
  [ 75.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here